fixed the Pegasus + Decaf simple example for the latest version of Decaf. Added some safeguards (Decaf and MPI checks) in the submit file too.
Signed-off-by: Loïc Pottier <lpottier@isi.edu>

diff --git a/share/pegasus/examples/decaf-linear2-nodes/submit b/share/pegasus/examples/decaf-linear2-nodes/submit
--- a/share/pegasus/examples/decaf-linear2-nodes/submit
+++ b/share/pegasus/examples/decaf-linear2-nodes/submit
@@ -12,6 +12,19 @@ BIN_DIR=`pegasus-config --bin`
 PEGASUS_LOCAL_BIN_DIR=$BIN_DIR
 export PEGASUS_LOCAL_BIN_DIR
 
+# Check if Decaf is found
+if [ -z "$DECAF_PREFIX" ]; then
+    echo "[ERROR]: DECAF_PREFIX must be set to the DECAF install path."
+    exit -1
+fi
+
+# Check if MPI is found
+MPI_VERSION=$(mpirun -V)
+if [ $? -eq 127 ]; then
+    echo "[ERROR]: mpirun must be in the PATH."
+    exit -1
+fi
+
 # generate the input file
 echo "This is sample input to KEG" >f.a
 
@@ -20,6 +33,9 @@ f.a file:///${TOPDIR}/f.a site="condorpool"
 EOF
 
 # generate the dax
+if [ -z "$DYLD_LIBRARY_PATH" ]; then
+    export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
+fi
 
 # plan and submit the  workflow
 pegasus-plan \
