PM-989 fix for output files check.

diff --git a/bin/pegasus-analyzer b/bin/pegasus-analyzer
--- a/bin/pegasus-analyzer
+++ b/bin/pegasus-analyzer
@@ -1265,6 +1265,20 @@ def debug_condor(my_job):
         debug_script.write("\n")
         debug_script.write("set -e\n")
         debug_script.write("\n")
+
+        debug_script.write( """
+check_file() {
+file=$1
+echo "Status is $STATUS"
+if [ -e $file ]; then
+    return 0
+else
+    echo "ERROR: file $file not generated"
+STATUS=$(($STATUS + 1))
+fi
+}
+         """ )
+
         debug_script.write("export pegasus_lite_work_dir=%s" %debug_dir)
         debug_script.write("\n")
         debug_script.write("# Copy any files that are needed\n")
@@ -1322,8 +1336,29 @@ def debug_condor(my_job):
         debug_script.write('   echo "executable ran successfully"\n')
         debug_script.write("else\n")
         debug_script.write('   echo "executable failed with error $?"\n')
+        debug_script.write("   exit $rc\n")
         debug_script.write("fi\n")
-        debug_script.write("exit $rc\n")
+
+
+        #PM-989 add existence check for all output files transferred
+        #by condor file IO
+        debug_script.write( 'STATUS=0\n' )
+        debug_script.write( 'set +e \n')
+        for out_file in my_job.transfer_output_files.split(","):
+            if len(out_file):
+                debug_script.write("cp %s %s\n" % (my_file, debug_dir))
+
+        debug_script.write( """
+if [ $STATUS -eq 0 ]; then
+    echo "all output files were created"
+else
+    echo "ERROR: Not all output files were created"
+fi
+
+exit $STATUS
+        """)
+
+
     except:
         logger.error("cannot write to file %s" % (debug_script))
         sys.exit(1)
