Adjusting tests

diff --git a/test/core/027-montage-bypass-staging-site-condorio/run-bamboo-test b/test/core/027-montage-bypass-staging-site-condorio/run-bamboo-test
--- a/test/core/027-montage-bypass-staging-site-condorio/run-bamboo-test
+++ b/test/core/027-montage-bypass-staging-site-condorio/run-bamboo-test
@@ -92,7 +92,7 @@ echo
 echo "Adding input images to the replica catalog..."
 echo "  " `cat cache.list | wc -l` "images found"
 cat cache.list | grep -v ".fits " >rc.tmp
-perl -p -i -e 's/ipac/local/' rc.tmp
+perl -p -i -e 's/ipac_cluster/local/' rc.tmp
 cat url.list | sed 's/\.gz http/ http/' >> rc.tmp
 
 #we need to pull in the inputs first for this test
@@ -135,6 +135,10 @@ pegasus-plan \
 
 
 WORK_DIR=`cat $TOP_DIR/plan.out | grep pegasus-run | sed -E 's/.*pegasus-run[ ]+//'` 
+if [ "x$WORK_DIR" = "x" ]; then
+    echo "Unable to determine work directory from the planner output"
+    exit 1
+fi
 echo "work directory is $WORK_DIR"
 cd $WORK_DIR
 
