Merged changes for building pegasus 2045 and 2046 from trunk

diff --git a/release-tools/nmi/nmi-build-all b/release-tools/nmi/nmi-build-all
--- a/release-tools/nmi/nmi-build-all
+++ b/release-tools/nmi/nmi-build-all
@@ -29,8 +29,8 @@ source setup-devel.sh
 # which versions
 echo
 echo "##### Build tooling versions #####"
-java -version
-ant  -version
+java -version 2>&1
+ant  -version 2>&1
 
 # Pegasus version
 echo
@@ -71,71 +71,106 @@ ls -l -h
 # wms
 echo
 echo "##### Creating WMS package #####"
-cd $PEGASUS_HOME/dist
-# FIXME
-wget http://yggdrasil.isi.edu/~rynge/condor-packages/condor-7.4.1-linux-x86_64-rhel5.tar.gz
-tar xzf condor-*
-rm -f condor-*.tar.gz
-cd condor-*
-export CONDOR_DIR=`pwd`
 
-cd $PEGASUS_HOME/dist
-tar xzf ../tarballs/pegasus-binary-$PEGASUS_VERSION-$PEGASUS_SYSTEM.tar.gz
-mv pegasus-$PEGASUS_VERSION pegasus-wms-binary-$PEGASUS_VERSION
-export PEGASUS_DIR=`pwd`/pegasus-wms-binary-$PEGASUS_VERSION
+if [ ! -e $PEGASUS_HOME/../public ]; then
+    echo "WARNING: Skipping WMS package on this platform as Condor is missing"
+else
 
-cd pegasus-wms-*
-mkdir -p bin sbin etc lib var/spool libexec var/log man/man1
+    # we need to get condor from the NMI input
+    cd $PEGASUS_HOME/../public/v*/
+    
+    echo "Files provided by Condor build:"
+    ls -l
 
-# bin
-cd $CONDOR_DIR/bin
-for FILE in condor_dagman condor_q condor_submit condor_submit_dag condor_rm  condor_wait condor_status; do
-    cp -L $FILE $PEGASUS_DIR/bin/
-done
-cd $PEGASUS_DIR/bin/
-ln condor_rm condor_hold
-ln condor_rm condor_release
-
-# sbin
-cd $CONDOR_DIR/sbin
-for FILE in condor_c-gahp condor_c-gahp_worker_thread condor_gridmanager  condor_master condor \
-            condor_procd condor_schedd condor_vm-gahp gahp_server gt4_gahp nordugrid_gahp \
-            unicore_gahp condor_shadow condor_starter grid_monitor.sh condor_init; do
-    cp -L $FILE $PEGASUS_DIR/sbin/
-done
-cd $PEGASUS_DIR/sbin/
-ln condor condor_on
-ln condor condor_off
-ln condor condor_restart
-ln condor condor_vacate
-ln condor condor_reconfig
-ln condor condor_reschedule
-
-# lib
-cd $CONDOR_DIR/lib
-for FILE in glite gt4 gt4-gahp.jar ugahp.jar; do
-    cp -R -L $FILE $PEGASUS_DIR/lib/
-done
-
-# libexec
-cd $CONDOR_DIR/libexec
-for FILE in glite globus-gridftp-server gridftp_wrapper.sh; do
-    cp -R -L $FILE $PEGASUS_DIR/libexec/
-done
-
-# man
-cd $CONDOR_DIR/man/man1/
-for FILE in condor_hold.1 condor_master.1 condor_off.1 condor_on.1 condor_q.1 condor_release.1 \
-            condor_rm.1 condor_reschedule.1 condor_submit.1 condor_submit_dag.1; do
-    cp -L $FILE $PEGASUS_DIR/man/man1/
-done
-
-# condor config files
-cd $PEGASUS_HOME
-cp release-tools/nmi/condor* $PEGASUS_DIR/etc
-
-# appending to the setup scripts
-cat <<EOF >>$PEGASUS_DIR/setup.sh
+    echo "Removing files we do _not_ want..."
+    rm -f *.rpm *.sha1 *.md5
+    rm -f *unstripped*
+    rm -f *debug*
+    echo "Files left after first round of removal:"
+    ls -l
+    # some platforms only have dynamic builds - if so keep it - otherwise rm
+    NUM_TARS=`ls *.tar.gz | wc -l`
+    if [ $NUM_TARS -gt 1 ]; then
+        echo "$NUM_TARS tars still around - will remove dynamic builds"
+        rm -f *dynamic*
+    fi
+    echo "Files left after all pruning:"
+    ls -l
+    NUM_TARS=`ls *.tar.gz | wc -l`
+    if [ $NUM_TARS != 1 ]; then
+        echo "$NUM_TARS tars found - we expected 1 and only 1. Exiting..."
+        exit 1
+    fi
+    tar xzf *.tar.gz
+    rm *.tar.gz
+    cd condor-*
+    export CONDOR_DIR=`pwd`
+    
+    cd $PEGASUS_HOME/dist
+    tar xzf ../tarballs/pegasus-binary-$PEGASUS_VERSION-$PEGASUS_SYSTEM.tar.gz
+    mv pegasus-$PEGASUS_VERSION pegasus-wms-binary-$PEGASUS_VERSION
+    export PEGASUS_DIR=`pwd`/pegasus-wms-binary-$PEGASUS_VERSION
+    
+    cd pegasus-wms-*
+    mkdir -p bin sbin etc lib var/spool libexec var/log man/man1
+    
+    # bin
+    cd $CONDOR_DIR/bin
+    for FILE in condor_dagman condor_q condor_submit condor_submit_dag condor_rm  condor_wait condor_status; do
+        cp -L $FILE $PEGASUS_DIR/bin/
+    done
+    cd $PEGASUS_DIR/bin/
+    ln condor_rm condor_hold
+    ln condor_rm condor_release
+    
+    # sbin
+    cd $CONDOR_DIR/sbin
+    for FILE in condor_c-gahp condor_c-gahp_worker_thread condor_gridmanager  condor_master condor \
+                condor_procd condor_schedd condor_vm-gahp gahp_server gt4_gahp nordugrid_gahp \
+                unicore_gahp condor_shadow condor_starter grid_monitor.sh condor_init; do
+        if [ -e $FILE ]; then
+            cp -L $FILE $PEGASUS_DIR/sbin/
+        else
+            echo "WARNING: sbin/$FILE does not exist in Condor distribution"
+        fi
+    done
+    cd $PEGASUS_DIR/sbin/
+    ln condor condor_on
+    ln condor condor_off
+    ln condor condor_restart
+    ln condor condor_vacate
+    ln condor condor_reconfig
+    ln condor condor_reschedule
+    
+    # lib
+    cd $CONDOR_DIR/lib
+    for FILE in glite gt4 gt4-gahp.jar ugahp.jar; do
+        if [ -e $FILE ]; then
+            cp -R -L $FILE $PEGASUS_DIR/lib/
+        else
+            echo "WARNING: lib/$FILE does not exist in Condor distribution"
+        fi
+    done
+    
+    # libexec
+    cd $CONDOR_DIR/libexec
+    for FILE in glite globus-gridftp-server gridftp_wrapper.sh; do
+        cp -R -L $FILE $PEGASUS_DIR/libexec/
+    done
+    
+    # man
+    cd $CONDOR_DIR/man/man1/
+    for FILE in condor_hold.1 condor_master.1 condor_off.1 condor_on.1 condor_q.1 condor_release.1 \
+                condor_rm.1 condor_reschedule.1 condor_submit.1 condor_submit_dag.1; do
+        cp -L $FILE $PEGASUS_DIR/man/man1/
+    done
+    
+    # condor config files
+    cd $PEGASUS_HOME
+    cp release-tools/nmi/condor* $PEGASUS_DIR/etc
+    
+    # appending to the setup scripts
+    cat <<EOF >>$PEGASUS_DIR/setup.sh
 PATH=\$PEGASUS_HOME/sbin:\$PATH
 export PATH
 CONDOR_CONFIG=\$PEGASUS_HOME/etc/condor_config
@@ -145,12 +180,13 @@ cat <<EOF >>$PEGASUS_DIR/setup.csh
 setenv PATH \${PEGASUS_HOME}/sbin:\${PATH}
 setenv CONDOR_CONFIG \${PEGASUS_HOME}/etc/condor_config
 EOF
-
-# tar up the results
-cd $PEGASUS_HOME/dist/
-tar czf ../tarballs/pegasus-wms-binary-$PEGASUS_VERSION-$PEGASUS_SYSTEM.tar.gz \
-        pegasus-wms-binary-$PEGASUS_VERSION
-rm -rf pegasus-wms-binary-$PEGASUS_VERSION condor-*
+    
+    # tar up the results
+    cd $PEGASUS_HOME/dist/
+    tar czf ../tarballs/pegasus-wms-binary-$PEGASUS_VERSION-$PEGASUS_SYSTEM.tar.gz \
+            pegasus-wms-binary-$PEGASUS_VERSION
+    rm -rf pegasus-wms-binary-$PEGASUS_VERSION condor-*
+fi
 
 echo
 echo "##### Build completed successfully #####"
