#2129 Changes to use the latest Python version available on the platform instead of the lowest version available

diff --git a/release-tools/get-system-python b/release-tools/get-system-python
--- a/release-tools/get-system-python
+++ b/release-tools/get-system-python
@@ -12,10 +12,6 @@ for CANDIDATE in $PEGASUS_PYTHON \
             /usr/bin/python3.12 \
             /usr/bin/python3.11 \
             /usr/bin/python3.10 \
-            /usr/bin/python3.9 \
-            /usr/bin/python3.8 \
-            /usr/bin/python3.7 \
-            /usr/bin/python3.6 \
             `which python3 2>/dev/null` \
     ; do
     if [ -e "$CANDIDATE" ]; then
@@ -33,8 +29,8 @@ fi
 MAJOR=`$PEXE -V 2>&1 | sed -e 's/^.* \([0-9]*\)\.[0-9].*$/\1/'`
 MINOR=`$PEXE -V 2>&1 | sed -e 's/^.* [0-9]*\.\([0-9]*\).*$/\1/'`
 
-if [ $MAJOR = 3 -a $MINOR -lt 6 ]; then
-    echo "ERROR: Pegasus requires at least Python 3.6" >&2
+if [ $MAJOR = 3 -a $MINOR -lt 10 ]; then
+    echo "ERROR: Pegasus requires at least Python 3.10" >&2
     exit 1
 fi
 
