PM-1235: Switching to Python 3

diff --git a/release-tools/get-system-python b/release-tools/get-system-python
--- a/release-tools/get-system-python
+++ b/release-tools/get-system-python
@@ -2,27 +2,40 @@
 
 set -e
 
-# allow override for users who really do not like the system python
-# note that this can cause issues with the worker package as
-# jobs can land on a system with a different python
-if [ "x$PEGASUS_PYTHON" != "x" ]; then
-    echo "$PEGASUS_PYTHON"
-    exit 0
+# PEGASUS_PYTHON - allow override for users who really do not
+# like the system python
+
+# Look for a python in a pre-determined order, prefer Python3
+for PEXE in $PEGASUS_PYTHON \
+            /usr/bin/python3.7 \
+            /usr/bin/python3.6 \
+            `which python3 2>/dev/null` \
+    ; do
+    if [ -e "$PEXE" ]; then
+        break
+    fi
+done
+
+if [ "x$PEXE" = "x" ]; then
+    echo "ERROR: Unable to find Python!" >&2
+    exit 1
 fi
 
-# determine the version of /usr/bin/python
-VERSION=`/usr/bin/python -V 2>&1 | sed -e 's/^.* \([0-9]\.[0-9]\).*$/\1/'`
+# determine the version
+MAJOR=`$PEXE -V 2>&1 | sed -e 's/^.* \([0-9]*\)\.[0-9].*$/\1/'`
+MINOR=`$PEXE -V 2>&1 | sed -e 's/^.* [0-9]*\.\([0-9]*\).*$/\1/'`
 
-if ! (echo "$VERSION" | grep "^2") >/dev/null 2>&1; then
-    echo "WARNING: Pegasus has only been tested with Python 2.6 and 2.7" >&2
+if [ $MAJOR = 3 -a $MINOR -lt 5 ]; then
+    echo "ERROR: Pegasus requires at least Python 3.5" >&2
+    exit 1
 fi
 
 # to be specific, expand the path if possible
-if [ -e "/usr/bin/python$VERSION" ]; then
-    echo "/usr/bin/python$VERSION"
+if [ -e "$PEXE$MAJOR.$MINOR" ]; then
+    echo "$PEXE$MAJOR.$MINOR"
     exit 0
 fi
 
-echo "/usr/bin/python"
+echo "$PEXE"
 
 
