Updated NMI build scripts

diff --git a/release-tools/nmi/submit-host/platform-post b/release-tools/nmi/submit-host/platform-post
--- a/release-tools/nmi/submit-host/platform-post
+++ b/release-tools/nmi/submit-host/platform-post
@@ -2,6 +2,13 @@
 
 set -e
 
+/usr/bin/env
+
+if [ "x$_NMI_STEP_FAILED" != "x" ]; then
+    echo "Previous step failed, exiting\n" >&2
+    exit 1
+fi
+
 TOP_DIR=`pwd`
 
 rm -rf build-results
