For #2174 and #2176 check if the compute jobs submit file have the right value pegasus_memory_mb

diff --git a/test/core/052-condor_request/run-bamboo-test b/test/core/052-condor_request/run-bamboo-test
--- a/test/core/052-condor_request/run-bamboo-test
+++ b/test/core/052-condor_request/run-bamboo-test
@@ -22,21 +22,25 @@ fi
 echo "work directory is $WORK_DIR"
 cd $WORK_DIR
 
-
 # make sure certain bash variables have the right values
-for variable in pegasus_lite_enforce_strict_wp_check pegasus_lite_version_allow_wp_auto_download; do
-    echo "Searching for $variable"
-    for pegasus_lite_sh in `find $WORK_DIR -name \*ID\*.sh`; do
-        for match in `(grep $variable $pegasus_lite_sh | awk '{print $1;}') 2>/dev/null `; do
-            # variable can appear twice in the pegasus lite script
-	    #echo "match is $match"
-	    if (echo $match | grep $variable  | grep "false" ) >/dev/null 2>&1; then
-		echo "Error: $pegasus_lite_sh has $variable set to false. Should be true"
-		exit 1
-            fi
-        done
-    done
+variable="pegasus_memory"
+expected_value="ifthenelse( (LastHoldReasonCode=!=34 && LastHoldReasonCode=!=26), InitialRequestMemory, int(1.75 * NumJobStarts * MemoryUsage) )"
+echo "Searching for $variable"
+
+for submit_file in `find $WORK_DIR -name \*.sub`; do
+    basename=`basename $submit_file`
+    if [[ ! $basename =~ clean_* ]] && [[  ! $basename =~ stage_* ]] && [[  ! $basename =~ create_* ]] && [[  ! $basename =~ register_* ]] && [[  ! $basename =~ .*dag.condor.sub ]] ; then
+        pegasus_memory_mb=`grep -E "^\+$variable"  $submit_file | sed -E 's/^\+pegasus_memory_mb\s+=\s+//'` 2>/dev/null
+        #echo "pegasus memory is $pegasus_memory_mb"
+
+        if [ "x$pegasus_memory_mb" != "x$expected_value" ]; then
+            echo "ERROR: +$variable is not set to value $expected_value in the submit file $submit_file"
+            echo "Instead it is set to $pegasus_memory_mb"
+            exit 1
+        fi
+    fi
 done
+
 
 # now we are good to submit
 echo "Submitting the workflow for execution"
