Extra checks for planner failures

diff --git a/test/common/check-status b/test/common/check-status
--- a/test/common/check-status
+++ b/test/common/check-status
@@ -1,13 +1,19 @@
-#!/bin/bash                                                                                                                                                                                                                                                       
-echo "CURRENT DIR is " `pwd`
-echo "Checking status "
+#!/bin/bash
 
-TIMEOUT=180
-COUNT=0
 function update_status
 {
    STATUS=`pegasus-status --noqueue | tail -1 | sed 's/[:\(\)]/ /g'| awk '{print $5}'`
 }
+
+echo "CURRENT DIR is " `pwd`
+
+if [ ! -e braindump.txt ]; then
+    echo "braindump.txt was not found in this directory. Planner probably failed!" 1>&2
+    exit 1
+fi
+
+TIMEOUT=180
+COUNT=0
 
 sleep 1m
 update_status
@@ -37,3 +43,4 @@ else
     echo "*** Workflow failed ***"
     exit 1
 fi
+
diff --git a/test/scripts/launch-bamboo-test b/test/scripts/launch-bamboo-test
--- a/test/scripts/launch-bamboo-test
+++ b/test/scripts/launch-bamboo-test
@@ -26,6 +26,12 @@ fi
 
 #Get RUNDIR from the planning output
 RUN_DIR=`grep pegasus-remove $PLANFILE | awk '{print $5}'`
+
+if [ "x$RUN_DIR" = "x" ]; then
+    echo "Unable to determine the RUN_DIR from the planner output - did the planner fail?" 1>&2
+    exit 1
+fi
+
 echo "RUNDIR is $RUN_DIR"
 
 # Change in to the rundir
@@ -44,9 +50,13 @@ fi
 if [ $STATUS = 0 ]; then
    # Run Pegasus Statistics
    pegasus-statistics -s all $RUN_DIR
-else 
-   echo "ERROR: Test failed"
+   STATUS=$?
+fi
+
+if [ $STATUS != 0 ]; then
+   echo "ERROR: Test failed" 1>&2
    exit $STATUS
 fi
 
 exit
+
