PM-1386 failsafe check to ensure no stagein jobs are created.

diff --git a/test/core/043-integrity-bypass-staging-b/run-bamboo-test b/test/core/043-integrity-bypass-staging-b/run-bamboo-test
--- a/test/core/043-integrity-bypass-staging-b/run-bamboo-test
+++ b/test/core/043-integrity-bypass-staging-b/run-bamboo-test
@@ -1,7 +1,22 @@
 #!/bin/bash
 
-set -e 
+set -e
+set -o pipefail
+TOP_DIR=`pwd`
 
 echo "Running blackdiamond.py"
 export PYTHONPATH=`pegasus-config --python`
-python3 blackdiamond.py
+python3 blackdiamond.py 2>&1 | tee $TOP_DIR/plan.out
+
+
+WORK_DIR=`cat plan.out | grep pegasus-remove | sed -E 's/.*pegasus-remove[ ]+(.*)[ ]+/\1/'`
+# account for deep submit directory structure
+cd $WORK_DIR/00/00
+
+NUM_JOBS=`find $WORK_DIR -name "stage_in*sub" | wc -l`
+
+if [ "$NUM_JOBS" -gt "0" ]; then
+    echo "ERROR: planner created $NUM_JOBS stage_in jobs . It should have created 0 as bypass is set for all files in workflow"
+    exit 1
+fi
+
