Removed requirements on PEGASUS_HOME and setup.sh

diff --git a/examples/grid-rosetta-sls/submit b/examples/grid-rosetta-sls/submit
--- a/examples/grid-rosetta-sls/submit
+++ b/examples/grid-rosetta-sls/submit
@@ -26,6 +26,14 @@ CLUSTER_GLOBUS_LOCATION="/nfs/software/osg-wn/current/globus"
 TOPDIR=`pwd`
 LOCAL_HOSTNAME=`hostname -f`
 
+# figure out where Pegasus is installed
+export PEGASUS_HOME=`which pegasus-plan | sed 's:/bin/pegasus-plan::'`
+if [ "x$PEGASUS_HOME" = "x" ]; then
+    echo "Unable to determine location of your Pegasus install"
+    echo "Please make sure pegasus-plan is in your path"
+    exit 1
+fi 
+
 # do we have the required minirosetta_database?
 if [ ! -e minirosetta_database ]; then
    wget -nv http://www.isi.edu/~rynge/pegasus/example-workflows/minirosetta_database.tar.gz
@@ -41,7 +49,7 @@ if [ ! -e pdbs ]; then
 fi
 
 # build the dax generator
-export CLASSPATH=.:$CLASSPATH
+export CLASSPATH=.:$PEGASUS_HOME/lib/pegasus.jar:$CLASSPATH
 javac RosettaDAX.java
 
 # generate the dax
@@ -89,7 +97,6 @@ cat >sites.xml <<EOF
             </storage>
         </head-fs>
         <replica-catalog  type="LRC" url="rlsn://dummyValue.url.edu" />
-        <profile namespace="pegasus" key="bundle.stagein" >4</profile>
         <profile namespace="env" key="GLOBUS_LOCATION" >$CLUSTER_GLOBUS_LOCATION</profile>
         <profile namespace="env" key="wmtmp" >$CLUSTER_WN_TMP</profile>
     </site>
diff --git a/examples/grid-rosetta/submit b/examples/grid-rosetta/submit
--- a/examples/grid-rosetta/submit
+++ b/examples/grid-rosetta/submit
@@ -14,14 +14,18 @@ CLUSTER_GRID_TYPE="gt5"
 CLUSTER_SCHEDULER="condor"
 CLUSTER_WORK_DIR="/nfs/ccg1/90-day-scratch"
 CLUSTER_GLOBUS_LOCATION="/cluster-software/globus/5.0.1"
-
-# you can cluster shorter jobs into a bundle of jobs - in this
-# case we want to bundle all rosetta jobs into 30 GRAM jobs
-#JOB_CLUSTERING="PEGASUS::clust=30"
 #######################################################################
 
 
 TOPDIR=`pwd`
+
+# figure out where Pegasus is installed
+export PEGASUS_HOME=`which pegasus-plan | sed 's:/bin/pegasus-plan::'`
+if [ "x$PEGASUS_HOME" = "x" ]; then
+    echo "Unable to determine location of your Pegasus install"
+    echo "Please make sure pegasus-plan is in your path"
+    exit 1
+fi 
 
 # do we have the required minirosetta_database?
 if [ ! -e minirosetta_database ]; then
@@ -38,7 +42,7 @@ if [ ! -e pdbs ]; then
 fi
 
 # build the dax generator
-export CLASSPATH=.:$CLASSPATH
+export CLASSPATH=.:$PEGASUS_HOME/lib/pegasus.jar:$CLASSPATH
 javac RosettaDAX.java
 
 # generate the dax
