added common properties to test-no-jobs

diff --git a/test/scripts/launch-bamboo-test-no-jobs b/test/scripts/launch-bamboo-test-no-jobs
--- a/test/scripts/launch-bamboo-test-no-jobs
+++ b/test/scripts/launch-bamboo-test-no-jobs
@@ -13,6 +13,15 @@ cd test/core/$TEST
 echo "TEST is $TEST"
 pwd
 
+#add common properties to pegasusrc
+if [ -e pegasusrc ]; then
+    echo "" >> pegasusrc
+    cat ../common.properties >> pegasusrc
+else
+    echo "ERROR Test $TEST not setup with pegasusrc file"
+    exit 1
+fi
+
 #Launch the test
 ./run-bamboo-test "$@"
 
