Add common properties for all test cases. this where we set pegasus.metrics.app and will set pegasus.catalog.master.url in future

diff --git a/test/scripts/launch-bamboo-test b/test/scripts/launch-bamboo-test
--- a/test/scripts/launch-bamboo-test
+++ b/test/scripts/launch-bamboo-test
@@ -25,6 +25,14 @@ pwd
 
 PLANFILE=`mktemp plan.XXXXXX`
 
+#add common properties to pegasusrc
+if [ -e pegasusrc ]; then
+    cat ../common.properties >> pegasusrc
+else
+    echo "ERROR Test $TEST not setup with pegasusrc file"
+    exit 1
+fi
+
 #Launch the test
 ./run-bamboo-test "$@" | tee $PLANFILE
 
diff --git a/test/scripts/launch-bamboo-test-planner-only b/test/scripts/launch-bamboo-test-planner-only
--- a/test/scripts/launch-bamboo-test-planner-only
+++ b/test/scripts/launch-bamboo-test-planner-only
@@ -17,6 +17,14 @@ pwd
 # redirect output to plan.out. no double teeing
 PLANFILE=plan.out
 
+#add common properties to pegasusrc
+if [ -e pegasusrc ]; then
+    cat ../common.properties >> pegasusrc
+else
+    echo "ERROR Test $TEST not setup with pegasusrc file"
+    exit 1
+fi
+
 #Launch the test
 ./run-bamboo-test "$@" 
 
