Bamboo tests will now check for ERROR in planner stdout

diff --git a/test/scripts/launch-bamboo-test b/test/scripts/launch-bamboo-test
--- a/test/scripts/launch-bamboo-test
+++ b/test/scripts/launch-bamboo-test
@@ -34,6 +34,12 @@ if [ $STATUS != 0 ]; then
    exit $STATUS
 fi
 
+# check for bad planner outputs
+if grep 'ERROR' $PLANFILE >/dev/null 2>&1; then
+    echo "The planner logged a line with the string 'ERROR'"
+    exit 1
+fi
+
 #Get RUNDIR from the planning output
 RUN_DIR=`grep pegasus-remove $PLANFILE | awk '{print $5}'`
 if [ "x$RUN_DIR" = "x" ]; then
